"""Add subscription billing and merged main tables.

Revision ID: 38193b41fbf4
Revises: 20260905_0004
Create Date: 2026-09-05 16:20:11.607505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38193b41fbf4'
down_revision: Union[str, None] = '20260905_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cadence', sa.Enum('monthly', 'quarterly', 'yearly', name='subscription_cadence_enum'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_index(op.f('ix_subscription_plans_product_id'), 'subscription_plans', ['product_id'], unique=False)
    op.create_table('cancellation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('refund_type', sa.Enum('full', 'partial', 'none', name='refund_type_enum'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellation_rules_plan_id'), 'cancellation_rules', ['plan_id'], unique=False)
    op.create_table('discount_anomaly_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.Column('discount_given', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rep_average_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_anomaly_flags_quotation_id'), 'discount_anomaly_flags', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_discount_anomaly_flags_rep_id'), 'discount_anomaly_flags', ['rep_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Unpaid', 'Paid', 'PartiallyPaid', name='invoice_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_quotation_id'), 'invoices', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('negotiation_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Resolved', name='negotiation_status_enum'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_threads_quotation_id'), 'negotiation_threads', ['quotation_id'], unique=True)
    op.create_table('portal_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_accesses_access_token_hash'), 'portal_accesses', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_portal_accesses_customer_id'), 'portal_accesses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_portal_accesses_quotation_id'), 'portal_accesses', ['quotation_id'], unique=False)
    op.create_table('proration_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proration_rules_plan_id'), 'proration_rules', ['plan_id'], unique=False)
    op.create_table('stalled_deal_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('days_inactive', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stalled_deal_flags_quotation_id'), 'stalled_deal_flags', ['quotation_id'], unique=True)
    op.create_table('billing_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_line_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Scheduled', 'Billed', 'Failed', name='schedule_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_schedules_billing_date'), 'billing_schedules', ['billing_date'], unique=False)
    op.create_index(op.f('ix_billing_schedules_plan_id'), 'billing_schedules', ['plan_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_quotation_line_id'), 'billing_schedules', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_status'), 'billing_schedules', ['status'], unique=False)
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_table('negotiation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('quotation_line_id', sa.Integer(), nullable=True),
    sa.Column('author_type', sa.Enum('Customer', 'Rep', name='negotiation_author_type_enum'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('Comment', 'Change Request', 'Counter Discount', name='negotiation_message_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('proposed_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['negotiation_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_messages_author_id'), 'negotiation_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_quotation_line_id'), 'negotiation_messages', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_thread_id'), 'negotiation_messages', ['thread_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.drop_constraint(op.f('approval_requests_quotation_id_key'), 'approval_requests', type_='unique')
    op.create_index(op.f('ix_approval_requests_quotation_id'), 'approval_requests', ['quotation_id'], unique=True)
    op.create_index(op.f('ix_approval_steps_approval_request_id'), 'approval_steps', ['approval_request_id'], unique=False)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_foreign_key(None, 'fulfillment_split_lines', 'warehouses', ['warehouse_id'], ['id'])
    op.alter_column('fulfillment_split_lines', 'warehouse_id', nullable=True)
    op.create_index(op.f('ix_price_list_entries_price_list_id'), 'price_list_entries', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_entries_product_id'), 'price_list_entries', ['product_id'], unique=False)
    op.add_column('quotation_lines', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quotation_lines_plan_id'), 'quotation_lines', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'quotation_lines', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'quotation_lines', type_='foreignkey')
    op.drop_index(op.f('ix_quotation_lines_plan_id'), table_name='quotation_lines')
    op.drop_column('quotation_lines', 'plan_id')
    op.drop_index(op.f('ix_price_list_entries_product_id'), table_name='price_list_entries')
    op.drop_index(op.f('ix_price_list_entries_price_list_id'), table_name='price_list_entries')
    op.drop_constraint(None, 'fulfillment_split_lines', type_='foreignkey')
    op.alter_column('fulfillment_split_lines', 'warehouse_id', nullable=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_approval_steps_approval_request_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_requests_quotation_id'), table_name='approval_requests')
    op.create_unique_constraint(op.f('approval_requests_quotation_id_key'), 'approval_requests', ['quotation_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_negotiation_messages_thread_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_quotation_line_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_author_id'), table_name='negotiation_messages')
    op.drop_table('negotiation_messages')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_billing_schedules_status'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_quotation_line_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_plan_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_billing_date'), table_name='billing_schedules')
    op.drop_table('billing_schedules')
    op.drop_index(op.f('ix_stalled_deal_flags_quotation_id'), table_name='stalled_deal_flags')
    op.drop_table('stalled_deal_flags')
    op.drop_index(op.f('ix_proration_rules_plan_id'), table_name='proration_rules')
    op.drop_table('proration_rules')
    op.drop_index(op.f('ix_portal_accesses_quotation_id'), table_name='portal_accesses')
    op.drop_index(op.f('ix_portal_accesses_customer_id'), table_name='portal_accesses')
    op.drop_index(op.f('ix_portal_accesses_access_token_hash'), table_name='portal_accesses')
    op.drop_table('portal_accesses')
    op.drop_index(op.f('ix_negotiation_threads_quotation_id'), table_name='negotiation_threads')
    op.drop_table('negotiation_threads')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_quotation_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_discount_anomaly_flags_rep_id'), table_name='discount_anomaly_flags')
    op.drop_index(op.f('ix_discount_anomaly_flags_quotation_id'), table_name='discount_anomaly_flags')
    op.drop_table('discount_anomaly_flags')
    op.drop_index(op.f('ix_cancellation_rules_plan_id'), table_name='cancellation_rules')
    op.drop_table('cancellation_rules')
    op.drop_index(op.f('ix_subscription_plans_product_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
