import { api } from '../api.js';
import { modal } from '../components/modal.js';

const fallbackPlans = [
  { id: 1, name: 'Enterprise M&A Platform Core', cadence: 'yearly', price: 120000, product_id: 1 },
  { id: 2, name: 'Deal Desk Executive Seat', cadence: 'monthly', price: 350, product_id: 2 },
  { id: 3, name: 'Mission-Critical 24/7 Support SLA', cadence: 'yearly', price: 45000, product_id: 3 },
];
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`;
const cadence = (value) => (value || 'yearly').replace(/^./, (letter) => letter.toUpperCase());

export function renderSubscriptionsPage(plans = []) {
  const list = Array.isArray(plans) && plans.length ? plans : fallbackPlans;
  const active = list.filter((plan) => plan.is_active !== false && plan.status !== 'Canceled');
  const mrr = list.reduce((total, plan) => total + Number(plan.price || 0) / ((plan.cadence || '').toLowerCase() === 'monthly' ? 1 : 12), 0);
  const rows = list.map((plan, index) => {
    const cycle = cadence(plan.cadence);
    const state = plan.is_active === false || plan.status === 'Canceled' ? 'Canceled' : 'Active';
    return `<a class="subscription-row" href="#/subscriptions/${plan.id}" data-search="${`${plan.name} ${plan.id} ${plan.product_id}`.toLowerCase()}">
      <div class="subscription-plan-cell"><div class="icon-circle bg-surface-container-high/60"><span class="material-symbols-outlined text-primary">${index % 2 ? 'memory' : 'cloud_sync'}</span></div><div class="min-w-0"><strong class="block text-sm text-on-surface truncate">${plan.name}</strong><span class="text-[11px] text-on-surface-variant"><span class="font-mono">SUB-${String(plan.id).padStart(4, '0')}</span> · Product ${plan.product_id || 'N/A'} · ${cycle} entitlement</span></div></div>
      <div><strong class="block text-sm text-on-surface">${plan.customer_name || 'Unassigned account'}</strong><span class="text-[11px] text-on-surface-variant">${plan.tier || 'Enterprise'} · Master agreement</span></div>
      <div><strong class="font-mono text-sm text-on-surface">${money(plan.price)} <span class="text-[11px] font-sans text-on-surface-variant">/ ${cycle === 'Monthly' ? 'mo' : 'yr'}</span></strong><span class="block text-[11px] text-on-surface-variant">${cycle} recurring billing</span></div>
      <div><strong class="font-mono text-xs text-on-surface">${plan.next_bill || (index % 2 ? 'Nov 30, 2026' : 'Dec 15, 2026')}</strong><span class="block text-[11px] text-primary">Auto-renewal on</span></div>
      <div><span class="badge ${state === 'Active' ? 'badge-success' : 'badge-warning'} text-[10px]">${state}</span></div><span class="subscription-row-arrow material-symbols-outlined" aria-hidden="true">chevron_right</span>
    </a>`;
  }).join('');

  return `<div class="page-container space-y-6">
    <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div class="flex items-center gap-2 mb-1"><span class="pulse-dot"></span><span class="text-xs font-bold text-primary tracking-widest uppercase">Billing engine active · Ledger OK</span></div><h1 class="text-2xl font-bold tracking-tight text-on-surface">Subscriptions &amp; Recurring Billing</h1><p class="text-sm text-on-surface-variant">Manage recurring contracts, renewal timing, and billing schedules across customer entities.</p></div><button type="button" class="btn btn-primary text-xs" id="btn-add-plan"><span class="material-symbols-outlined text-base">add_circle</span><span>New Subscription Plan</span></button></div>
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4"><div class="card card-extruded subscription-metric"><span>Active MRR Run-Rate</span><strong>${money(mrr)}<small>/mo</small></strong><em>ARR: ${money(mrr * 12)}</em></div><div class="card card-extruded subscription-metric"><span>Active Subscriptions</span><strong>${active.length}</strong><em>${active.length} active contracts</em></div><div class="card card-extruded subscription-metric"><span>Gross Monthly Churn</span><strong>0.8%<small>vol/mo</small></strong><em>Benchmark &lt; 1.50%</em></div><div class="card card-extruded subscription-metric"><span>Auto-Renewal Pacing</span><strong>94.6%<small>secured</small></strong><em>45 in 60-day horizon</em></div></div>
    <section class="card card-extruded subscription-workspace"><div class="flex flex-col xl:flex-row items-stretch xl:items-center justify-between gap-3 mb-4"><div class="subscription-filters" role="tablist"><button type="button" class="subscription-filter active" data-filter="all">All Subscriptions <b>${list.length}</b></button><button type="button" class="subscription-filter" data-filter="active">Active <b>${active.length}</b></button><button type="button" class="subscription-filter" data-filter="renewal">Renewal Due <b>0</b></button><button type="button" class="subscription-filter" data-filter="suspended">Suspended / Trial <b>0</b></button></div><label class="subscription-search"><span class="material-symbols-outlined">search</span><input id="subscription-search" type="search" placeholder="Search customer, plan ID, or tag..." /></label></div><div class="subscription-table-head"><span>Plan &amp; entitlement</span><span>Customer entity</span><span>Commit value &amp; cycle</span><span>Next bill</span><span>State</span><span></span></div><div id="subscription-rows" class="space-y-2">${rows}</div><p id="subscription-empty" class="hidden text-center text-sm text-on-surface-variant py-8">No subscriptions match this view.</p><div class="flex items-center justify-between gap-3 pt-4 text-xs text-on-surface-variant"><span>Showing <strong class="text-on-surface">${list.length}</strong> of ${list.length} recurring contracts</span><span class="font-mono">Page 1</span></div></section>
    <section class="card card-extruded space-y-4"><div class="flex items-center gap-2"><span class="material-symbols-outlined text-primary">calculate</span><div><h3 class="text-base font-bold">Mid-Cycle Seat Upgrade &amp; Proration</h3><p class="text-xs text-on-surface-variant">Preview the delta before changing a recurring contract.</p></div></div><div class="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs"><label>Active plan<select class="input-clay w-full mt-1" id="prorate-plan"><option value="4200">Executive Seats (₹4,200/yr)</option><option value="120000">Enterprise Core (₹120k/yr)</option></select></label><label>Seats added<input type="number" id="prorate-seats" min="1" value="5" class="input-clay w-full mt-1" /></label><label>Days remaining<input type="number" id="prorate-days" min="1" max="365" value="142" class="input-clay w-full mt-1" /></label><label>Proration delta<div class="font-mono font-bold text-base text-primary p-2 mt-1 rounded-lg bg-surface-container" id="prorate-result">₹8,169.86</div></label></div></section>
  </div>`;
}

export async function loadSubscriptions() { try { return await api.get('/subscriptions/plans'); } catch { return []; } }

export function setupSubscriptionsEvents() {
  const search = document.getElementById('subscription-search'); const rows = [...document.querySelectorAll('.subscription-row')]; const empty = document.getElementById('subscription-empty'); const filters = [...document.querySelectorAll('.subscription-filter')]; let filter = 'all';
  const apply = () => { const term = (search?.value || '').toLowerCase().trim(); let visible = 0; rows.forEach((row) => { const matchSearch = !term || row.dataset.search.includes(term); const matchFilter = filter !== 'active' || row.querySelector('.badge-success'); row.classList.toggle('hidden', !matchSearch || !matchFilter); if (matchSearch && matchFilter) visible += 1; }); empty?.classList.toggle('hidden', visible > 0); };
  search?.addEventListener('input', apply); filters.forEach((button) => button.addEventListener('click', () => { filter = button.dataset.filter; filters.forEach((item) => item.classList.toggle('active', item === button)); apply(); }));
  const seats = document.getElementById('prorate-seats'); const days = document.getElementById('prorate-days'); const plan = document.getElementById('prorate-plan'); const result = document.getElementById('prorate-result'); const recalculate = () => { if (result) result.textContent = money((Number(plan?.value) / 365) * Number(days?.value || 0) * Number(seats?.value || 0)); }; [seats, days, plan].forEach((input) => input?.addEventListener('input', recalculate));
  document.getElementById('btn-add-plan')?.addEventListener('click', () => modal.show({ title: 'New Subscription Plan', content: '<input id="plan-name-in" type="text" class="input-clay w-full" placeholder="Plan name" /><input id="plan-price-in" type="number" class="input-clay w-full mt-3" placeholder="Base rate (INR)" />', confirmText: 'Create Plan', onConfirm: async () => { const name = document.getElementById('plan-name-in').value.trim(); const price = Number(document.getElementById('plan-price-in').value); if (!name || !price) throw new Error('Plan name and price are required'); await api.post('/subscriptions/plans', { name, cadence: 'yearly', product_id: 1, price }); window.location.reload(); return true; } }));
}
