import { api } from '../api.js';
import { modal } from '../components/modal.js';

const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
const label = (value) => (value || 'yearly').replace(/^./, (letter) => letter.toUpperCase());

export function renderSubscriptionDetailPage(detail) {
  if (!detail?.id) return `<div class="page-container flex items-center justify-center min-h-[60vh]"><div class="card card-extruded p-8 text-center"><span class="material-symbols-outlined text-4xl text-outline mb-3">error_outline</span><h2 class="text-lg font-bold">Subscription Not Found</h2><a href="#/subscriptions" class="btn btn-primary text-xs mt-4">Back to Subscriptions</a></div></div>`;
  const schedules = detail.schedules || [];
  const billed = schedules.filter((item) => item.status === 'Billed').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const scheduled = schedules.filter((item) => item.status === 'Scheduled').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const rows = schedules.length ? schedules.map((item) => `<tr class="border-b border-surface-container-high/40"><td class="py-3 px-4 font-mono text-xs">${item.projected ? 'PROJECTED' : `BILL-${String(item.id).padStart(5, '0')}`}</td><td class="py-3 px-4 font-mono text-xs">${item.billing_date || 'Scheduled'}</td><td class="py-3 px-4 text-xs">${item.customer_name || detail.customers?.[0] || 'Unassigned account'}</td><td class="py-3 px-4 font-mono text-xs text-right font-bold">${money(item.amount)}</td><td class="py-3 px-4"><span class="badge ${item.status === 'Billed' ? 'badge-success' : 'badge-warning'} text-[10px]">${item.status || 'Scheduled'}</span></td></tr>`).join('') : `<tr><td colspan="5" class="py-8 text-center text-xs text-on-surface-variant">No billing cycles have been generated for this subscription yet.</td></tr>`;
  const active = detail.is_active !== false;
  return `<div class="page-container space-y-6"><div class="flex items-center gap-3"><a href="#/subscriptions" class="btn btn-secondary text-xs py-1.5 px-3"><span class="material-symbols-outlined text-sm">arrow_back</span><span>Back to Subscriptions</span></a><span class="text-xs text-outline">/</span><span class="text-xs font-mono font-bold text-primary">SUB-${String(detail.id).padStart(4, '0')}</span></div>
    <div class="card card-extruded"><div class="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div class="flex items-center gap-4"><div class="w-14 h-14 rounded-2xl bg-surface-container flex items-center justify-center text-primary"><span class="material-symbols-outlined text-3xl">receipt_long</span></div><div><div class="flex items-center gap-2 flex-wrap"><h1 class="text-xl font-bold text-on-surface">Billing Detail</h1><span class="badge ${active ? 'badge-success' : 'badge-error'} text-[10px]">${active ? 'Active' : 'Canceled'}</span></div><p class="text-sm font-bold text-on-surface mt-1">${detail.name}</p><p class="text-xs text-on-surface-variant mt-1">Product ${detail.product_id} · ${label(detail.cadence)} recurring contract</p></div></div><div class="flex items-center gap-2">${active ? '<button type="button" class="btn btn-secondary text-xs" id="btn-modify-subscription"><span class="material-symbols-outlined text-sm">edit_note</span><span>Modify Terms</span></button><button type="button" class="btn btn-secondary text-xs text-error" id="btn-cancel-subscription"><span class="material-symbols-outlined text-sm">bolt</span><span>Cancel Contract</span></button>' : ''}</div></div></div>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4"><div class="card card-extruded subscription-detail-stat"><span>Contract Value</span><strong>${money(detail.price)}</strong><em>per ${label(detail.cadence).toLowerCase()} cycle</em></div><div class="card card-extruded subscription-detail-stat"><span>Billed To Date</span><strong>${money(billed)}</strong><em>${schedules.filter((item) => item.status === 'Billed').length} settled cycles</em></div><div class="card card-extruded subscription-detail-stat"><span>Scheduled Balance</span><strong>${money(scheduled)}</strong><em>${schedules.filter((item) => item.status === 'Scheduled').length} upcoming cycles</em></div></div>
    <section class="card card-extruded"><div class="flex items-center justify-between gap-3 mb-4"><div><h2 class="text-base font-bold">Billing Schedule</h2><p class="text-xs text-on-surface-variant">Every generated charge for this recurring contract.</p></div><span class="badge badge-primary text-[10px]">${schedules.length} cycles</span></div><div class="overflow-x-auto rounded-xl bg-surface-container-lowest border border-surface-container-high/60"><table class="w-full text-left border-collapse"><thead><tr class="border-b border-surface-container-high/60 bg-surface-container-low/50 text-[11px] font-bold text-on-surface-variant uppercase tracking-wider"><th class="py-2.5 px-4">Billing reference</th><th class="py-2.5 px-4">Billing date</th><th class="py-2.5 px-4">Customer entity</th><th class="py-2.5 px-4 text-right">Amount</th><th class="py-2.5 px-4">Status</th></tr></thead><tbody>${rows}</tbody></table></div></section>
    <section class="card card-extruded"><div class="flex items-center gap-2 mb-3"><span class="material-symbols-outlined text-primary">account_balance</span><h2 class="text-base font-bold">Remittance &amp; Contract Context</h2></div><div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs"><div><span class="detail-label">Customer entity</span><strong>${detail.customers?.join(', ') || 'Unassigned account'}</strong></div><div><span class="detail-label">Payment terms</span><strong>Net 30 · Direct wire</strong></div><div><span class="detail-label">Ledger status</span><strong class="text-primary">Reconciled and monitored</strong></div></div></section></div>`;
}

export async function loadSubscriptionDetail(planId) { try { return await api.get(`/subscriptions/plans/${planId}/billing-detail`); } catch (error) { console.warn('Could not fetch subscription billing detail:', error); return null; } }

export function setupSubscriptionDetailEvents(detail) {
  document.getElementById('btn-modify-subscription')?.addEventListener('click', () => modal.show({ title: 'Modify Subscription Terms', content: `<div class="space-y-3 text-xs"><label class="block font-bold">Plan name<input id="modify-plan-name" class="input-clay w-full mt-1" value="${detail.name}" /></label><label class="block font-bold">Recurring price (INR)<input id="modify-plan-price" type="number" min="0.01" class="input-clay w-full mt-1" value="${detail.price}" /></label><label class="block font-bold">Cadence<select id="modify-plan-cadence" class="input-clay w-full mt-1"><option value="monthly" ${detail.cadence === 'monthly' ? 'selected' : ''}>Monthly</option><option value="quarterly" ${detail.cadence === 'quarterly' ? 'selected' : ''}>Quarterly</option><option value="yearly" ${detail.cadence === 'yearly' ? 'selected' : ''}>Yearly</option></select></label></div>`, confirmText: 'Save Terms', onConfirm: async () => { await api.patch(`/subscriptions/plans/${detail.id}`, { name: document.getElementById('modify-plan-name').value.trim(), price: Number(document.getElementById('modify-plan-price').value), cadence: document.getElementById('modify-plan-cadence').value }); window.location.hash = `#/subscriptions/${detail.id}`; window.location.reload(); return true; } }));
  document.getElementById('btn-cancel-subscription')?.addEventListener('click', () => {
    const line = detail?.schedules?.find((item) => item.quotation_line_id)?.quotation_line_id;
    modal.show({ title: 'Cancel Subscription', content: '<p class="text-xs text-on-surface-variant">Future billing cycles will stop and this contract will be marked canceled.</p>', confirmText: 'Cancel Contract', onConfirm: async () => { if (line) await api.post(`/subscriptions/lines/${line}/cancel`, {}); else await api.post(`/subscriptions/plans/${detail.id}/cancel`, {}); window.location.hash = '#/subscriptions'; window.location.reload(); return true; } });
  });
}
